package org.cap.cc.batch.dao;

public enum CustomLoggingEvents {
	BATCH_STARTED, BATCH_FINISHED,
	STARTED_PROCESSING_TASK,
	SUBMIT_CHECKLIST,
	STARTED_CHECKING_THUNDERHEAD_JOB_STATUS, FINISHED_CHECKING_THUNDERHEAD_JOB_STATUS,
	BATCH_ERROR, BATCH_EXCEPTION
}
